"""Added tables

Revision ID: 1c42e5ac0266
Revises: 46c5832e564c
Create Date: 2018-02-13 19:12:06.906764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c42e5ac0266'
down_revision = '46c5832e564c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['metal_id'], ['metal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metal_id'], ['metal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('coin')
    op.drop_table('metal')
    # ### end Alembic commands ###
