"""Added Price.value

Revision ID: c6f4ea29b1c5
Revises: 1c42e5ac0266
Create Date: 2018-02-13 19:27:11.924428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f4ea29b1c5'
down_revision = '1c42e5ac0266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
