"""Added Metal.symbol

Revision ID: fe24c2a02e4a
Revises: c6f4ea29b1c5
Create Date: 2018-02-13 19:34:40.879133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe24c2a02e4a'
down_revision = 'c6f4ea29b1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
